version: "3.9"

services:
  client:
    container_name: 'client'
    image: "ricebowl-client:latest"
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=development
volumes:
  mongodb:
